# Assignment for week 4

Use the following table to provide us with

|name | exam number|
|----|----|
|Anton Andersen| 186827|
|Ting Chen| 920623|

In this assignment, we will play around with functions and use the `fsolve` routine to solve an equation.

First, we need to import some libraries.

Recall that you need to have installed plotly for this to work. Further, you need to register at the plotly website.

In [1]:
from scipy import optimize

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.graph_objs import Bar, Scatter, Figure, Layout
init_notebook_mode(connected=True)
from numpy import arange


Let us define the function $f(x) = x^2+c$ which is a function of $x$ for a given value of $c$.

In [3]:
def my_function(x,c):
    return x**2 + c

Now we would like to solve $x^2 + c =0$. As this is a simple equation, you can this analytically. This helps us to understand how `fsolve` works.

If you want to know more about `fsolve`, simply google "python fsolve".

For our purposes here, we call `fsolve` as `optimize.fsolve`, then we give a function and an initial value where `fsolve` starts looking for a solution. `fsolve` uses numerical techniques to find the "zero" of a function; it does not solve the equation analytically. Roughly speaking, it looks at a value of $x$ whether it is above or below 0. If it is below 0, it needs to change $x$ in such a way that $f(x)$ increases. It uses the derivative $f'(x)$ to figure out whether it should increase or decrease $x$ to get to $f(x)=0$. So suppose that $f(x) < 0$ and $f'(x) >0$ then it will increase $x$ (move to the right) to a solution to $f(x) =0$.

As `my_function` is actually a function of two variables ($x$ and $c$), we define a new "anonymous" function `lambda` that is only a function of $x$ and we solve for this function to 0. Say, we start looking for a solution at $x=1$, then we type:

In [3]:
optimize.fsolve(lambda x: my_function(x,-2),+1)


array([ 1.41421356])

This only gives one solution? But with a quadratic equation, there are usually two solutions. In the following cell give the python command to give the other solution:

In [4]:
optimize.fsolve(lambda x: my_function(x,-2),-1)


array([-1.41421356])

Now try the following cell. Explain below why you get an error message; $x=0$ does not solve this equation?

In [5]:
optimize.fsolve(lambda x: my_function(x,-2),0)

C:\Users\aande\Downloads\Viktigaste apps\lib\site-packages\scipy\optimize\minpack.py:161: RuntimeWarning:

The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.



array([ 0.])

Because, with any given value x*0 will always equal to 0. Therefore, lambda*0 cannot be a non zero constant, so the function can never be 0.

Now we let's consider another function, with $c = 2$ (instead of $c = -2$). Explain below why we get an error this time

In [6]:
optimize.fsolve(lambda x: my_function(x,2),-1)

C:\Users\aande\Downloads\Viktigaste apps\lib\site-packages\scipy\optimize\minpack.py:161: RuntimeWarning:

The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.



array([-0.00097656])

it is due to the fact that x^2 will never be a negative number, thus adding this number to a positive number will not be 0.

Now define the function $f(x) = \frac{1}{x}$ in python:

In [6]:
def my_function2(x):
    return 1/x

and use plotly to plot this function for $x > 0$. Adjust the range for $x$ so that you get a "decent" graph.

In [7]:
import numpy as np
range_x = arange(0.03,1.01,0.01)
range_x

array([ 0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ,  0.11,
        0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ,
        0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,
        0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,
        0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,
        0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,  0.54,  0.55,  0.56,
        0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,  0.63,  0.64,  0.65,
        0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,  0.72,  0.73,  0.74,
        0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,  0.81,  0.82,  0.83,
        0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ,  0.91,  0.92,
        0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ])

In [12]:
iplot([{"x": range_x, "y": my_function2(range_x)}])

In [10]:
optimize.fsolve(lambda x: my_function2(x)-0.5,1)

array([ 2.])